print ("*************** tabuada em python difícil de fazer************")
n = int(input (" digite um numero para a taboada de 1 até 10 = "))
print ( "1 x {} = {} ".format( n , n * 1))
print ( "2 x {} = {} ".format(n  , n * 2))
print ( "1 x {} = {} ".format( n , n * 3))     
print ( "1 x {} = {} ".format( n , n * 4))
print ( "1 x {} = {} ".format( n , n * 5))
print ( "1 x {} = {} ".format( n , n * 6))
print ( "1 x {} = {} ".format( n , n * 7))
print ( "1 x {} = {} ".format( n , n * 8))
print ( "1 x {} = {} ".format( n , n * 9))
print ( "1 x {} = {} ".format( n , n * 10))